/**
 * Created by haoxiaotian on 2016/9/1 18:59.
 * version 1.0
 */
-- DROP DATABASE IF EXISTS `COURSE_DESIGN_2016`;
-- CREATE DATABASE `COURSE_DESIGN_2016`;
-- USE `COURSE_DESIGN_2016`;

CREATE TABLE AUTH_USER(
    `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
    `PHONE` BIGINT NOT NULL COMMENT '手机号',
    `ID_CARD` CHAR(20) NOT NULL DEFAULT 0 COMMENT '身份证号',
    `USERNAME` VARCHAR(60) NOT NULL COMMENT '用户名',
    `PASSWORD` CHAR(32) NOT NULL COMMENT '密码',
    `SALT` CHAR(32) NOT NULL COMMENT 'MD5 盐',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `DELETE_MARK` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志：0（正常）；-1（已删除）',
     KEY phone_index(PHONE) COMMENT '根据手机号 B+ 树索引'
#    TODO:索引根据具体查询，后期再加
 )ENGINE = INNODB AUTO_INCREMENT = 1 CHARSET=UTF8 COMMENT = '系统用户表';

CREATE TABLE AUTH_ROLE(
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '角色ID',
  `NAME` VARCHAR(255) NOT NULL COMMENT '角色名',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `DELETE_MARK` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志：0（正常）；-1（已删除）'
#    TODO:索引根据具体查询，后期再加
)ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET=UTF8 COMMENT = '系统角色表';

CREATE TABLE AUTH_MENU(
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '菜单ID',
  `NAME` VARCHAR(255) NOT NULL COMMENT '显示菜单名称',
  `ICON` VARCHAR(50) NULL COMMENT '图标类型',
  `PARENT_ID` INT NOT NULL DEFAULT -1 COMMENT '父菜单ID（-1：无父菜单）',
  `URL` VARCHAR(255) NOT NULL DEFAULT 'NULL' COMMENT '点击菜单跳转URL',
  `SORT_NUM` TINYINT NOT NULL DEFAULT 1 COMMENT '同级菜单排列顺序',
  `ACCORDION` TINYINT NOT NULL DEFAULT 0 COMMENT '是否是顶级菜单（0：否；1：是）',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `DELETE_MARK` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志：0（正常）；-1（已删除）'
#    TODO:索引根据具体查询，后期再加
)ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET=UTF8 COMMENT = '系统菜单表';

CREATE TABLE AUTH_USER_ROLE(
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` INT NOT NULL COMMENT '用户ID',
  `ROLE_ID` INT NOT NULL COMMENT '角色ID',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  FOREIGN KEY REF_USER_KEY (USER_ID) REFERENCES AUTH_USER (ID),
  FOREIGN KEY REF_ROLE_KEY (ROLE_ID) REFERENCES AUTH_ROLE (ID)
#    TODO:索引根据具体查询，后期再加
)ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET=UTF8 COMMENT =  '系统\'用户-角色\'对应表';


CREATE TABLE AUTH_ROLE_MENU(
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
  `ROLE_ID` INT NOT NULL COMMENT '角色ID',
  `MENU_ID` INT NOT NULL COMMENT '菜单ID',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  FOREIGN KEY REF_ROLE_KEY (ROLE_ID) REFERENCES AUTH_ROLE (ID),
  FOREIGN KEY REF_MENU_KEY (MENU_ID) REFERENCES AUTH_MENU (ID)
#    TODO:索引根据具体查询，后期再加
)ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET=UTF8 COMMENT = '系统\'角色-菜单\'对应表';


# 初始化管理员用户(username:admin   password:123456)
SET @SALT = TIMESTAMPDIFF(SECOND, '1970-1-1 8:0:0', CURDATE());
SET @SALT = MD5(@SALT);
SET @PASSWORD = '123456';
SET @PASSWORD = MD5(CONCAT(MD5(@PASSWORD),@SALT));
INSERT INTO AUTH_USER(PHONE,ID_CARD,USERNAME,PASSWORD,SALT)
    VALUES ('15122938076','130131199504140016','admin',@PASSWORD,@SALT);

# SET @SALT = 'd697e13df61eafc4b3777e1d74697c6e';
# SELECT MD5(CONCAT(MD5('123456'),@SALT));

INSERT INTO AUTH_ROLE(NAME)
    VALUES ('系统管理员');

INSERT INTO AUTH_USER_ROLE(USER_ID, ROLE_ID)
    VALUES (1,1);

INSERT INTO AUTH_MENU(ID,NAME,ICON, PARENT_ID, URL, SORT_NUM, ACCORDION)
    VALUES
#     顶级菜单 START
      (1,'首页','icon-home',-1,'/index_dynamic.jsp',1,1),
      (2,'系统管理','icon-cogs',-1,'NULL',2,1),
      (3,'假务管理','icon-file-text',-1,'NULL',3,1),
      (4,'加班管理','icon-briefcase',-1,'NULL',4,1),
#      顶级菜单 END

#      二级菜单 START
      (5,'用户管理','',2,'/users_dynamic.jsp',1,0),
      (6,'角色管理','',2,'/roles_dynamic.jsp',2,0),

      (7,'未批复','',3,'NULL',1,0),
      (8,'休假记录','',3,'NULL',2,0),
      (9,'类型管理','',3,'NULL',3,0);

#      二级菜单 END

INSERT INTO AUTH_ROLE_MENU(ROLE_ID, MENU_ID)
    VALUES (1,1),
            (1,2),
            (1,3),
            (1,4),
            (1,5),
            (1,6),
            (1,7),
            (1,8),
            (1,9);





# 初始化管理员用户(username:admin   password:123456)
SET @SALT = TIMESTAMPDIFF(SECOND, '1970-1-1 8:0:0', CURDATE());
SET @SALT = MD5(@SALT);
SET @PASSWORD = '123456';
SET @PASSWORD = MD5(CONCAT(MD5(@PASSWORD),@SALT));
INSERT INTO AUTH_USER(PHONE,ID_CARD,USERNAME,PASSWORD,SALT)
VALUES ('15620947182','130131199504140013','汤宏垚',@PASSWORD,@SALT);

# SET @SALT = 'd697e13df61eafc4b3777e1d74697c6e';
# SELECT MD5(CONCAT(MD5('123456'),@SALT));

INSERT INTO AUTH_ROLE(NAME)
VALUES ('假务员');

INSERT INTO AUTH_USER_ROLE(USER_ID, ROLE_ID)
VALUES (2,2);

INSERT INTO AUTH_ROLE_MENU(ROLE_ID, MENU_ID)
VALUES (2,1),
  (2,3),
  (2,4),
  (2,7),
  (2,8),
  (2,9);
